version: '3.2'

# by Anton Dziavitsyn
# spark cluster compose example

services:
  spark-master:
    image: muritiku/spark-master
    ports:
      - "8080:8080"
      - "4040:4040"
      - "7077:7077"
    networks:
      spark-network:
        aliases:
          - spark-master

  spark-worker-1:
    image: muritiku/spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "4041:4041"
      - "7078:7078"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - 'spark-master'
    networks:
      spark-network:
        aliases:
          - spark-worker-1

networks:
  spark-network:
    # driver: overlay # for docker stack deploy
